# Generated by Django 2.0.6 on 2019-03-30 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190329_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coretext',
            name='url',
        ),
    ]
