# Generated by Django 2.0.6 on 2019-03-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_coretext_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='coretext',
            name='order',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
