# Generated by Django 2.0.6 on 2019-03-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_coretext_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coretext',
            name='order',
        ),
        migrations.AddField(
            model_name='coretext',
            name='child',
            field=models.IntegerField(null=True),
        ),
    ]
