# Generated by Django 2.0.6 on 2019-10-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190330_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coretext',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('head', 'Head'), ('math', 'Math')], max_length=5),
        ),
    ]
