# Generated by Django 2.0.6 on 2019-10-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191020_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='coretext',
            name='parent',
            field=models.IntegerField(null=True),
        ),
    ]
