# Generated by Django 2.0.6 on 2019-11-02 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_coretext_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('child', models.IntegerField(null=True)),
                ('parent', models.IntegerField(null=True)),
                ('level', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='coretext',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Directory'),
        ),
    ]
