# Generated by Django 2.0.6 on 2019-12-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191103_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coretext',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('head', 'Head'), ('math', 'Math'), ('code', 'Code')], max_length=5),
        ),
    ]
