# Generated by Django 2.0.6 on 2019-12-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191219_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coretext',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('head', 'Head'), ('math', 'Math'), ('code', 'Code'), ('markdown', 'Markdown')], max_length=5),
        ),
    ]
