# Generated by Django 2.0.6 on 2020-01-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coretext',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('head', 'Head'), ('math', 'Math'), ('code', 'Code'), ('md', 'Md'), ('link', 'Link')], max_length=5),
        ),
    ]
